fhaa/views/auth_views.py
"""
회원가입/가입완료 페이지를 위한 블루프린트
Authors: jlee (junlee9834@gmail.com)
"""

from flask import Blueprint, render_template, request, url_for, session, g, flash
from fhaa.forms import UserCreateForm, HospitalCreateForm
from fhaa.models import User, Hospital, HosSub, Subject
from fhaa import db
from werkzeug.utils import redirect
from werkzeug.security import generate_password_hash
import functools
from fhaa.libs import gps

bp = Blueprint('auth', __name__, url_prefix='/signup')


@bp.route('/')
def signup():
    return render_template('auth/signup.html')


@bp.route('/patient/', methods=('GET', 'POST'))
def patient_signup():
    if g.user is None:
        form = UserCreateForm()
        
        if request.method == 'POST' and form.validate_on_submit():
            user = User.query.filter_by(pat_ema=form.email.data).first()
            # user가 없으면 새로운 user를 생성하고 auth.congrats로 리다이렉트
            if not user:
                user = User(pat_ema=form.email.data,
                            pat_name=form.name.data,
                            pat_pw=generate_password_hash(form.password1.data),
                            pat_tel=form.phone.data,
                            pat_bir=form.birth.data)
                
                db.session.add(user)
            
                db.session.commit()
                
                return redirect(url_for('auth.congrats', user_id=form.email.data, user_name=form.name.data), code=307)
            else:
                flash('이미 존재하는 사용자입니다.')
                
        return render_template('auth/patient_signup.html', form=form)
    
    else:
        return redirect(url_for('main.index'))


@bp.route('/hospital/', methods=('GET', 'POST'))
def hospital_signup():
    if g.user is None:
        form = HospitalCreateForm()
        if request.method == 'POST' and form.validate_on_submit() and g.user is None: 
            user = Hospital.query.filter_by(hos_cid=form.crn.data).first()
            if not user:
                hospital_location = gps.get_location(form.address1.data)

                user = Hospital(
                            hos_cid=form.crn.data,
                            hos_pwd=generate_password_hash(form.password1.data),
                            hos_name=form.name.data,
                            hos_addr1=form.address1.data,
                            hos_addr2=form.address2.data,
                            hos_tel=form.tel.data,
                            hos_lat=str(hospital_location[0]),
                            hos_lnt=str(hospital_location[1]),
                            hos_type=''
                        )
                db.session.add(user)
                db.session.commit()
                
                for ill_pid in form.subject.data:
                    hossub = HosSub(hos_cid=user.hos_cid, ill_pid=ill_pid)
                    db.session.add(hossub)
                db.session.commit()
                    
                # 가입완료 페이지에서 id와 name을 표시하기 위함
                return redirect(url_for('auth.congrats', user_id=user.hos_cid, user_name=user.hos_name), code=307)
            else:
                flash('이미 존재하는 사용자입니다.')
                
        return render_template('auth/hospital_signup.html', form=form)
    
    else:
        return redirect(url_for('main.index'))


@bp.route('/congrats', methods=('GET', 'POST'))
def congrats():
    if request.method == 'POST' :
        user_id = request.args.get('user_id')
        request.get_data()
        user_name = request.args.get('user_name')
        print(user_id, user_name)
        return render_template('auth/congrats.html', user_id=user_id, user_name=user_name)
    else:
        return redirect(url_for('main.index'))


def login_required_all(view):
    """모든 사용자로 로그인 후 이용할 수 있는 서비스에 사용됨
    """
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('login.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view


def login_required_for_patient(view):
    """환자로 로그인 후 이용할 수 있는 서비스에 사용됨
    """
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is not None and type(g.user) == Hospital:
            return redirect(url_for('main.index'))
        return view(*args, **kwargs)
    return wrapped_view


def login_required_for_hospital(view):
    """병원으로 로그인 후 이용할 수 있는 서비스에 사용됨
    """
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is not None and type(g.user) == User:
            return redirect(url_for('main.index'))
        return view(*args, **kwargs)
    return wrapped_view

fhaa/views/log_views.py
from flask import Blueprint, render_template, session, request, flash, url_for, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from fhaa import db
from fhaa.forms import UserLoginForm, HospitalLoginForm
from fhaa.models import User, Hospital, Subject
import datetime

bp = Blueprint('login',__name__,url_prefix='/login')


@bp.route('/', methods=('GET','POST'))
def login():
    return render_template('log/login.html')


@bp.route('/pat/', methods=('GET','POST'))
def pat_login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(pat_ema=form.email.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.pat_pw, form.password.data):
            error = "비밀번호가 일치하지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.pat_ema
            session['user_type'] = "patient"
            print(user)
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('log/pat_login.html', form=form)


@bp.route('/hos/', methods=('GET','POST'))
def hos_login():
    form = HospitalLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = Hospital.query.filter_by(hos_cid=form.crn.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.hos_pwd, form.password.data):
            error = "비밀번호가 일치하지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.hos_cid
            session['user_type'] = "hospital"
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('log/hos_login.html', form=form)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))


# @bp.before_app_request
# def load_logged_in_user():
#     user_id = session.get('user_id')
#     user_type = session.get('user_type')
#     if user_id is None:
#         g.user = None
#         g.user_type = None
#     elif user_type == "patient":
#         g.user = User.query.get(user_id)
#         g.user_type = user_type
#         g.user_name = g.user.pat_name
#     elif user_type == "patient":
#         g.user = User.query.get(user_id)
#         g.user_type = user_type
#         g.user_name = g.user.pat_name
    
        

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    user_type = session.get('user_type')
    
    if user_id is None or user_type is None:
        g.user = None
        g.user_type = None
    else:
        g.user_type = user_type
        if user_type == 'patient':
            g.user = User.query.get(user_id)    
            # if g.user != None: 
            #     g.user_name = g.user.pat_name
            # else : 
            #     g.user_name = "guest"
            #     g.user = User.query.get(user_id)         
            # g.user_name = g.user.pat_name
            
        elif user_type == 'hospital':
            g.user = Hospital.query.get(user_id)
            # g.user_name = g.user.hos_name

fhaa/templates/log/hos_login.html
{% extends "base.html" %}
{% block content %}
<div class="container w-50" style="margin-top: 7rem;">
  <div class="form-signin">
    <label class="form-label mb-3"><h3 style="color:4c2a80; margin-left: 23px;" >Login</h3></label>
    <div class="form-check">
      <form method="post">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}

        <div class="form-floating mb-3">
          <input type="text" class="form-control" id="floatingInput" name="crn" placeholder="사업자 등록번호10자리">
          <label for="floatingInput">사업자 등록번호</label>
        </div>
        <div class="form-floating mb-3">
          <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password">
          <label for="floatingInput">Password</label>
        </div>
        <div class="login">
          <button type="submit" class="btn btn-primary" style="width:100%">Login</button>
        </div>
        
        <div class="bs-component" style="margin-top: 10px;">
          <div class="alert alert-dismissible alert-primary">
            <strong>잠깐!</strong> <a href="{{ url_for('auth.hospital_signup') }}" class="alert-link">회원가입</a> 먼저 하시죠?
          </div>
        </div>
      </form>
    </div>
          
  </div>
</div>

{% endblock %}

{% block script %}
<script>
function myFunction() {
  if (chk_info="hospital"){
    document.getElementsByTagName("INPUT")[2].setAttribute("placeholder", "사업자번호")
  }
  else if (chk_info="user"){ 
    document.getElementsByTagName("INPUT")[2].setAttribute("placeholder", "email")
  }
}
</script>
{% endblock %}

fhaa/templates/log/login.html
{% extends "base.html" %}
{% block content %}
<!-- Authors: jlee (junlee9834@gmail.com) -->
<div class="container" style="margin-top: 7rem;">
    <div class="my-3 border-bottom pb-2"><h5 style="color: rgb(76, 42, 128);">Login</h5></div>
    <div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body d-flex flex-column align-items-center">
                <h5 class="card-title">일반 사용자</h5>
                <p class="card-text">일반 사용자로 로그인합니다.</p>
                <img class="w-25" src="{{ url_for('static', filename='patient.png') }}">
                <a href="{{ url_for('login.pat_login') }}"  class="btn btn-primary mt-3">일반 사용자 로그인</a>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body d-flex flex-column align-items-center">
                <h5 class="card-title">병원</h5>
                <p class="card-text">병원 계정으로 로그인합니다.</p>
                <img class="w-25" src="{{ url_for('static', filename='hospital.png') }}">
                <a href="{{ url_for('login.hos_login') }}" class="btn btn-primary mt-3">병원 로그인</a>
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}

fhaa/templates/log/pat_login.html
{% extends "base.html" %}
{% block content %}
<div class="container w-50" style="margin-top: 7rem;">
  <div class="form-signin">
      <label class="form-label mb-3"><h3 style="color:4c2a80; margin-left: 23px;" >Login</h3></label>
      <div class="form-check">
        <form method="post">
          {{ form.csrf_token }}
          {% include "form_errors.html" %}

          <div class="form-floating mb-3">
          <input type="email" class="form-control" name="email" id="email" placeholder="name@example.com" >
          <label for="email">Email address</label>
          </div>
          <div class="form-floating mb-3">
          <input type="password" class="form-control" name="password" id="password" placeholder="Password">
          <label for="password">Password</label>
          </div>
          <div class="login">
          <button type="submit" class="btn btn-primary" style="width:100%">Login</button>
          </div>
          <div class="bs-component" style="margin-top: 10px;">
                <div class="alert alert-dismissible alert-primary">
                  <strong>잠깐!</strong> <a href="{{ url_for('auth.patient_signup') }}" class="alert-link">회원가입</a> 먼저 하시죠?
                </div>
              </div>
        </form>    
      </div>
          
  </div>
</div>

{% endblock %}
{% block script %}
<script>
  function myFunction() {
    if (chk_info = "hospital") {
      document.getElementsByTagName("INPUT")[2].setAttribute("placeholder", "사업자번호")
    }
    else if (chk_info = "user") {
      document.getElementsByTagName("INPUT")[2].setAttribute("placeholder", "email")
    }
  }
</script>
{% endblock %}