fhaa/views/main_views.py
from flask import Blueprint, render_template
from fhaa.models import Hospital, HosSub, Subject
import sqlalchemy

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def index():
    return render_template('main/main.html')

@bp.route('/im')
def im():
    hos = Hospital.query.join(HosSub).join(Subject).filter(Hospital.hos_cid==HosSub.hos_cid, Subject.ill_type=="내과").all()

    return render_template('main/IM_adv.html',hoslist=hos)

@bp.route('/der')
def der():
    hos = Hospital.query.join(HosSub).join(Subject).filter(Hospital.hos_cid==HosSub.hos_cid, Subject.ill_type=="피부과").all()

    return render_template('main/DER_adv.html',hoslist=hos)

@bp.route('/uro')
def uro():
    hos = Hospital.query.join(HosSub).join(Subject).filter(Hospital.hos_cid==HosSub.hos_cid, Subject.ill_type=="비뇨의학과").all()

    return render_template('main/URO_adv.html',hoslist=hos)

@bp.route('/obgy')
def obgy():
    hos = Hospital.query.join(HosSub).join(Subject).filter(Hospital.hos_cid==HosSub.hos_cid, Subject.ill_type=="산부인과").all()

    return render_template('main/OBGY_adv.html',hoslist=hos)

@bp.route('/oph')
def oph():
    hos = Hospital.query.join(HosSub).join(Subject).filter(Hospital.hos_cid==HosSub.hos_cid, Subject.ill_type=="안과").all()

    return render_template('main/OPH_adv.html',hoslist=hos)

@bp.route('/os')
def os():
    hos = Hospital.query.join(HosSub).join(Subject).filter(Hospital.hos_cid==HosSub.hos_cid, Subject.ill_type=="정형외과").all()

    return render_template('main/OS_adv.html',hoslist=hos)

@bp.route('/ent')
def ent():
    hos = Hospital.query.join(HosSub).join(Subject).filter(Hospital.hos_cid==HosSub.hos_cid, Subject.ill_type=="이비인후과").all()

    return render_template('main/ENT_adv.html',hoslist=hos)

@bp.route('/dt')
def dt():
    hos = Hospital.query.join(HosSub).join(Subject).filter(Hospital.hos_cid==HosSub.hos_cid, Subject.ill_type=="치과").all()

    return render_template('main/DT_adv.html',hoslist=hos)

@bp.route('/pd')
def pd():
    hos = Hospital.query.join(HosSub).join(Subject).filter(Hospital.hos_cid==HosSub.hos_cid, Subject.ill_type=="소아과").all()

    return render_template('main/PD_adv.html',hoslist=hos)

fhaa/templates/main/DER_adv.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="margin-top: 7rem;">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="tables">피부과</h1>
    </div>
    <div class="row  row-cols-1 row-cols-md-2 g-2">
      <div class="col">
        <div class="card">
          <img class="card-img-top img-fluid" src="{{ url_for('static', filename='adv_page_img/DER-img.jpg') }}">
          <!-- <svg class="card-img-top" width="100%" height="180" src="{{ url_for('static', filename='IM-img.png') }}" xmlns="http://www.w3.org/2000/svg" role="img"  preserveAspectRatio="xMidYMid slice" ><title>Placeholder</title></svg> -->

          <div class="card-body">
            <h5 class="card-title">대표증상</h5>
            <p class="card-text">눈 주변에 구진 발생, 가려움, 구진과 물집 발생, 여드름, 티눈</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">병명</h5>
            <p class="card-text">
              <ul><b>기미:</b> 유전,호르몬의 영향에 의해서 멜라닌색소 생성 및 색소침착</ul>
              <ul><b>주근깨:</b> 불규칙적인 형태의 진한 갈색 색소가 표피층에 분포</ul>
              <ul><b>잡티:</b> 햇빛 노출이나 피부염, 모낭염 등 피부질환</ul>
              <ul><b>습진:</b> 가려움증을 동반한 피부질환</ul>
              <ul><b>아토피피부염:</b> 가려움을 동반하는 만성재발 습진질환</ul>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="bs-component">
      <table class="table table-hover mt-3">
        <thead>
          <tr class="table-primary">
            <th scope="col"> </th>
            <th scope="col">병원이름</th>
            <th scope="col">주소</th>
            <th scope="col">전화번호</th>
            
          </tr>
        </thead>
        <tbody>
          {%for hos in hoslist%}
          <tr class="table-secondary"> 
            <td> <span class="badge rounded-pill bg-info">추천</span></td>
            <td> {{hos.hos_name}}</td>
            {% if hos.hos_addr2 %}
              <td> {{ ", ".join((hos.hos_addr1,hos.hos_addr2)) }}</td>
            {% else %}
              <td> {{ hos.hos_addr1 }}</td>
            {% endif %}
            <td> {{hos.hos_tel}}</td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

fhaa/templates/main/DT_adv.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="margin-top: 7rem;">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="tables">치과</h1>
    </div>
    <div class="row  row-cols-1 row-cols-md-2 g-2">
      <div class="col">
        <div class="card">
          <img class="card-img-top img-fluid" src="{{ url_for('static', filename='adv_page_img/DT-img.jpg') }}">
          <!-- <svg class="card-img-top" width="100%" height="180" src="{{ url_for('static', filename='IM-img.png') }}" xmlns="http://www.w3.org/2000/svg" role="img"  preserveAspectRatio="xMidYMid slice" ><title>Placeholder</title></svg> -->

          <div class="card-body">
            <h5 class="card-title">대표증상</h5>
            <p class="card-text">잇몸 시림, 잇몸 감각 없음, 잇몸에서 피 남, 치아 변색</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">병명</h5>
            <p class="card-text">
              <ul><b>치주질환:</b>치아 주위조직에 나타나는 질환</ul>
              <ul><b>잇몸증식:</b>잇몸이 비정상적으로 자라남</ul>
              <ul><b>잇몸퇴축:</b>잇몸이 내려앉아 이 뿌리가 일부 노출되는 질환</ul>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="bs-component">
      <table class="table table-hover mt-3">
        <thead>
          <tr class="table-primary">
            <th scope="col"> </th>
            <th scope="col">병원이름</th>
            <th scope="col">주소</th>
            <th scope="col">전화번호</th>
            
          </tr>
        </thead>
        <tbody>
          {%for hos in hoslist%}
          <tr class="table-secondary"> 
            <td> <span class="badge rounded-pill bg-info">추천</span></td>
            <td> {{hos.hos_name}}</td>
            {% if hos.hos_addr2 %}
              <td> {{ ", ".join((hos.hos_addr1,hos.hos_addr2)) }}</td>
            {% else %}
              <td> {{ hos.hos_addr1 }}</td>
            {% endif %}
            <td> {{hos.hos_tel}}</td>
          {%endfor%}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

fhaa/templates/main/ENT_adv.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="margin-top: 7rem;">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="tables">이비인후과</h1>
    </div>
    <div class="row  row-cols-1 row-cols-md-2 g-2">
      <div class="col">
        <div class="card">
          <img class="card-img-top img-fluid" src="{{ url_for('static', filename='adv_page_img/ENT-img.jpg') }}">
          <!-- <svg class="card-img-top" width="100%" height="180" src="{{ url_for('static', filename='IM-img.png') }}" xmlns="http://www.w3.org/2000/svg" role="img"  preserveAspectRatio="xMidYMid slice" ><title>Placeholder</title></svg> -->

          <div class="card-body">
            <h5 class="card-title">대표증상</h5>
            <p class="card-text">콧물 많이 남, 이상한 냄새가 느껴짐, 냄새를 못 맡음, 기침 많이함, 침 삼킬 때 목아픔</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">병명</h5>
            <p class="card-text">
              <ul><b>메니에르병:</b>난청과 이명, 어지러움과 구토 유발</ul>
              <ul><b>이석증:</b>특정자세에서 반복적으로 어지럽고 자세변경하면 심해짐</ul>
              <ul><b>비염:</b>숨을 쉴 때 알레르기 반응을 일으켜 콧물, 재채기, 가려움증 유발</ul>
              <ul><b>중이염:</b>귓속이 붓고 중이가 막히면 잘 들리지 않을 수 있음.</ul>
              <ul><b>편도염:</b>여러 가지 원인으로 인해 전신의 저항력이 감소하였을 때 편도 내 세균으로 인해 급성 감염이 일어나는 질환</ul>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="bs-component">
      <table class="table table-hover mt-3">
        <thead>
          <tr class="table-primary">
            <th scope="col"> </th>
            <th scope="col">병원이름</th>
            <th scope="col">주소</th>
            <th scope="col">전화번호</th>
            
          </tr>
        </thead>
        <tbody>
          {%for hos in hoslist%}
          <tr class="table-secondary"> 
            <td><span class="badge rounded-pill bg-info">추천</span></td>
            <td> {{hos.hos_name}}</td>
            {% if hos.hos_addr2 %}
              <td> {{ ", ".join((hos.hos_addr1,hos.hos_addr2)) }}</td>
            {% else %}
              <td> {{ hos.hos_addr1 }}</td>
            {% endif %}
            <td> {{hos.hos_tel}}</td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

fhaa/templates/main/IM_adv.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="margin-top: 7rem;">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="tables">내과</h1>
    </div>
    <div class="row  row-cols-1 row-cols-md-2 g-2">
      <div class="col">
        <div class="card">
          <img class="card-img-top img-fluid" src="{{ url_for('static', filename='adv_page_img/IM-img.jpg') }}">
          <!-- <svg class="card-img-top" width="100%" height="180" src="{{ url_for('static', filename='IM-img.png') }}" xmlns="http://www.w3.org/2000/svg" role="img"  preserveAspectRatio="xMidYMid slice" ><title>Placeholder</title></svg> -->

          <div class="card-body">
            <h5 class="card-title">대표증상</h5>
            <p class="card-text">발열, 숨쉬기 힘듦, 멍이 잘듦, 소화불량, 헛배부름 느낌, 울렁거리고 구토함, 명치나 위가 아픔</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">병명</h5>
            <p class="card-text">
              <ul><b>위장질환:</b> 역류성 식도염, 기능성 위장 장애</ul>
              <ul><b>췌장질환:</b> 급·만성 췌장염, 췌장의 낭성 종양</ul>
              <ul><b>간질환:</b> 지방간, 간경변증, 간낭종</ul>
              <ul><b>담도질환:</b> 담낭염, 담석증</ul>
              <ul><b>대장질환:</b> 염증성 장질환(궤양성 대장염, 크론병), 대장염, 변비, 설사, 과민성 대장증후군</ul>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="bs-component">
      <table class="table table-hover mt-3">
        <thead>
          <tr class="table-primary">
            <th scope="col"> </th>
            <th scope="col">병원이름</th>
            <th scope="col">주소</th>
            <th scope="col">전화번호</th>
            
          </tr>
        </thead>
        <tbody>
          {%for hos in hoslist%}
          <tr class="table-secondary"> 
            <td> <span class="badge rounded-pill bg-info">추천</span></td>
            <td> {{hos.hos_name}}</td>
            {% if hos.hos_addr2 %}
              <td> {{ ", ".join((hos.hos_addr1,hos.hos_addr2)) }}</td>
            {% else %}
              <td> {{ hos.hos_addr1 }}</td>
            {% endif %}
            <td> {{ hos.hos_tel }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

fhaa/templates/main/OBGY_adv.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="margin-top: 7rem;">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="tables">산부인과</h1>
    </div>
    <div class="row  row-cols-1 row-cols-md-2 g-2">
      <div class="col">
        <div class="card">
          <img class="card-img-top img-fluid" src="{{ url_for('static', filename='adv_page_img/OBGY-img.jpg') }}">
          <!-- <svg class="card-img-top" width="100%" height="180" src="{{ url_for('static', filename='IM-img.png') }}" xmlns="http://www.w3.org/2000/svg" role="img"  preserveAspectRatio="xMidYMid slice" ><title>Placeholder</title></svg> -->

          <div class="card-body">
            <h5 class="card-title">대표증상</h5>
            <p class="card-text">누렇거나 회색 분비물, 아랫배 통증, 허리 통증, 골반 통증, 복부팽만, 복강내 전이로 인한 복통 </p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">병명</h5>
            <p class="card-text">
              <ul><b>자궁경부암:</b>자궁 입구인 자궁경부에 발생하는 악성종양</ul>
              <ul><b>질염:</b>질 내에 발생하는 염증(가장 흔한 질환) </ul>
              <ul><b>생리통:</b>일차성 생리통, 이차성 생리통(골반내 장기 이상에 의한 생리통)</ul>
              <ul><b>요실금:</b>힘이 많이 들어갈 때 의지와 상관없이 소변이 새는 증상</ul>
              <ul><b>난소암:</b>자궁의 부속기인 난소에 암이 생김(유전자 변이가 원인)</ul>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="bs-component">
      <table class="table table-hover mt-3">
        <thead>
          <tr class="table-primary">
            <th scope="col"> </th>
            <th scope="col">병원이름</th>
            <th scope="col">주소</th>
            <th scope="col">전화번호</th>
            
          </tr>
        </thead>
        <tbody>
          {%for hos in hoslist%}
          <tr class="table-secondary"> 
            <td> <span class="badge rounded-pill bg-info">추천</span></td>
            <td> {{hos.hos_name}}</td>
            {% if hos.hos_addr2 %}
              <td> {{ ", ".join((hos.hos_addr1,hos.hos_addr2)) }}</td>
            {% else %}
              <td> {{ hos.hos_addr1 }}</td>
            {% endif %}
            <td> {{hos.hos_tel}}</td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

fhaa/templates/main/OPH_adv.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="margin-top: 7rem;">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="tables">안과</h1>
    </div>
    <div class="row  row-cols-1 row-cols-md-2 g-2">
      <div class="col">
        <div class="card">
          <img class="card-img-top img-fluid" src="{{ url_for('static', filename='adv_page_img/OPH-img.jpg') }}">
          <!-- <svg class="card-img-top" width="100%" height="180" src="{{ url_for('static', filename='IM-img.png') }}" xmlns="http://www.w3.org/2000/svg" role="img"  preserveAspectRatio="xMidYMid slice" ><title>Placeholder</title></svg> -->

          <div class="card-body">
            <h5 class="card-title">대표증상</h5>
            <p class="card-text">눈 시림, 눈가려움, 충혈, 결막부종, 눈곱 많이낌, 다래끼</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">병명</h5>
            <p class="card-text">
              <ul><b>홍채염:</b>홍채의 염증으로 통증 및 시력 저하 유발</ul>
              <ul><b>각막염:</b>곰팡이, 바이러스에 의해 발생</ul>
              <ul><b>안구건조증:</b>눈물부족이 원인으로 충혈, 시력저하 유발</ul>
              <ul><b>백내장:</b>수정체의 변성으로 인해 뿌옇게 보이며 시력저하 유발</ul>
              <ul><b>노안:</b>수정체의 탄서이 저하되어 가까운 곳 볼 때 초점 흔들림</ul>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="bs-component">
      <table class="table table-hover mt-3">
        <thead>
          <tr class="table-primary">
            <th scope="col"> </th>
            <th scope="col">병원이름</th>
            <th scope="col">주소</th>
            <th scope="col">전화번호</th>
            
          </tr>
        </thead>
        <tbody>
          {%for hos in hoslist%}
          <tr class="table-secondary"> 
            <td><span class="badge rounded-pill bg-info">추천</span></td>
            <td>{{hos.hos_name}}</td>
            {% if hos.hos_addr2 %}
              <td> {{ ", ".join((hos.hos_addr1,hos.hos_addr2)) }}</td>
            {% else %}
              <td> {{ hos.hos_addr1 }}</td>
            {% endif %}
            <td> {{hos.hos_tel}}</td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

fhaa/templates/main/OS_adv.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="margin-top: 7rem;">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="tables">정형외과</h1>
    </div>
    <div class="row  row-cols-1 row-cols-md-2 g-2">
      <div class="col">
        <div class="card">
          <img class="card-img-top img-fluid" src="{{ url_for('static', filename='adv_page_img/OS-img.jpg') }}">
          <!-- <svg class="card-img-top" width="100%" height="180" src="{{ url_for('static', filename='IM-img.png') }}" xmlns="http://www.w3.org/2000/svg" role="img"  preserveAspectRatio="xMidYMid slice" ><title>Placeholder</title></svg> -->

          <div class="card-body">
            <h5 class="card-title">대표증상</h5>
            <p class="card-text">허리통증, 목 꺾이는 느낌 받음, 골절, 관절아픔, 손목 통증, 다리 부러진 것 같은 느낌 받음</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">병명</h5>
            <p class="card-text">
              <ul><b>족저근막염:</b>족저근막에 지속해서 과도한 압력이 가해져 통증 유발</ul>
              <ul><b>수부관절염:</b>주로 손가락에 발생해 관절의 통증과 변형 유발</ul>
              <ul><b>대상포진:</b>수두바이러스가 신경 뿌리에 잠복해 있다가 몸의 면역력이 약해지면서 발병</ul>
              <ul><b>오십견:</b>퇴행성 변화로 어깨 관절을 둘러싼 관절막에 염증 생김 및 통증 유발</ul>
              <ul><b>골다공증:</b>폐경, 노화 등의 여러가지 원인으로 발생하며 뼈에 구멍이 많아지는 질환</ul>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="bs-component">
      <table class="table table-hover mt-3">
        <thead>
          <tr class="table-primary">
            <th scope="col"> </th>
            <th scope="col">병원이름</th>
            <th scope="col">주소</th>
            <th scope="col">전화번호</th>
            
          </tr>
        </thead>
        <tbody>
          {%for hos in hoslist%}
          <tr class="table-secondary"> 
            <td> <span class="badge rounded-pill bg-info">추천</span></td>
            <td> {{hos.hos_name}}</td>
            {% if hos.hos_addr2 %}
              <td> {{ ", ".join((hos.hos_addr1,hos.hos_addr2)) }}</td>
            {% else %}
              <td> {{ hos.hos_addr1 }}</td>
            {% endif %}
            <td> {{hos.hos_tel}}</td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

fhaa/templates/main/main.html
{% extends "base.html" %}
{% block content %}
<!-- Page Content-->
<div class="container" style="margin-top: 7rem;">
<section class="pt-4">
    <div class="container px-lg-5">
        <!-- Page Features-->
        <div class="row gx-lg-5">
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <a href= "{{ url_for('main.im') }}" class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-collection"></i></div>
                        <img class="w-50 mb-3" src="{{ url_for('static', filename='main_page_img/medicine.png') }}">
                        <h2 class="fs-4 fw-bold">내과</h2>
                    </a>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <a href= "{{ url_for('main.der') }}" class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-cloud-download"></i></div>
                        <img class="w-50 mb-3" src="{{ url_for('static', filename='main_page_img/skin.png') }}">
                        <h2 class="fs-4 fw-bold">피부과</h2>
                    </a>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <a href= "{{ url_for('main.pd') }}" class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-patch-check"></i></div>
                        <img class="w-50 mb-3" src="{{ url_for('static', filename='main_page_img/children.png') }}">
                        <h2 class="fs-4 fw-bold">소아과</h2>
                    </a>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <a href= "{{ url_for('main.uro') }}" class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-card-heading"></i></div>
                        <img class="w-50 mb-3" src="{{ url_for('static', filename='main_page_img/urology.png') }}">
                        <h2 class="fs-4 fw-bold">비뇨의학과</h2>
                    </a>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <a href= "{{ url_for('main.obgy') }}" class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-bootstrap"></i></div>
                        <img class="w-50 mb-3" src="{{ url_for('static', filename='main_page_img/baby.png') }}">
                        <h2 class="fs-4 fw-bold">산부인과</h2>
                    </a>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <a href= "{{ url_for('main.oph') }}" class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-code"></i></div>
                        <img class="w-50 mb-3" src="{{ url_for('static', filename='main_page_img/eye.png') }}">
                        <h2 class="fs-4 fw-bold">안과</h2>
                    </a>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <a href= "{{ url_for('main.os') }}" class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-patch-check"></i></div>
                        <img class="w-50 mb-3" src="{{ url_for('static', filename='main_page_img/bone.png') }}">
                        <h2 class="fs-4 fw-bold">정형외과</h2>
                    </a>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <a href= "{{ url_for('main.ent') }}" class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-patch-check"></i></div>
                        <img class="w-50 mb-3" src="{{ url_for('static', filename='main_page_img/breath.png') }}">
                        <h2 class="fs-4 fw-bold">이비인후과</h2>
                    </a>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <a href= "{{ url_for('main.dt') }}" class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-patch-check"></i></div>
                        <img class="w-50 mb-3" src="{{ url_for('static', filename='main_page_img/teeth.png') }}">
                        <h2 class="fs-4 fw-bold">치과</h2>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
</div>
{% endblock %}