fhaa/views/auth_views.py
"""
회원가입/가입완료 페이지를 위한 블루프린트
Authors: jlee (junlee9834@gmail.com)
"""

from flask import Blueprint, render_template, request, url_for, session, g, flash
from fhaa.forms import UserCreateForm, HospitalCreateForm
from fhaa.models import User, Hospital, HosSub, Subject
from fhaa import db
from werkzeug.utils import redirect
from werkzeug.security import generate_password_hash
import functools
from fhaa.libs import gps

bp = Blueprint('auth', __name__, url_prefix='/signup')


@bp.route('/')
def signup():
    return render_template('auth/signup.html')


@bp.route('/patient/', methods=('GET', 'POST'))
def patient_signup():
    if g.user is None:
        form = UserCreateForm()
        
        if request.method == 'POST' and form.validate_on_submit():
            user = User.query.filter_by(pat_ema=form.email.data).first()
            # user가 없으면 새로운 user를 생성하고 auth.congrats로 리다이렉트
            if not user:
                user = User(pat_ema=form.email.data,
                            pat_name=form.name.data,
                            pat_pw=generate_password_hash(form.password1.data),
                            pat_tel=form.phone.data,
                            pat_bir=form.birth.data)
                
                db.session.add(user)
            
                db.session.commit()
                
                return redirect(url_for('auth.congrats', user_id=form.email.data, user_name=form.name.data), code=307)
            else:
                flash('이미 존재하는 사용자입니다.')
                
        return render_template('auth/patient_signup.html', form=form)
    
    else:
        return redirect(url_for('main.index'))


@bp.route('/hospital/', methods=('GET', 'POST'))
def hospital_signup():
    if g.user is None:
        form = HospitalCreateForm()
        if request.method == 'POST' and form.validate_on_submit() and g.user is None: 
            user = Hospital.query.filter_by(hos_cid=form.crn.data).first()
            if not user:
                hospital_location = gps.get_location(form.address1.data)

                user = Hospital(
                            hos_cid=form.crn.data,
                            hos_pwd=generate_password_hash(form.password1.data),
                            hos_name=form.name.data,
                            hos_addr1=form.address1.data,
                            hos_addr2=form.address2.data,
                            hos_tel=form.tel.data,
                            hos_lat=str(hospital_location[0]),
                            hos_lnt=str(hospital_location[1]),
                            hos_type=''
                        )
                db.session.add(user)
                db.session.commit()
                
                for ill_pid in form.subject.data:
                    hossub = HosSub(hos_cid=user.hos_cid, ill_pid=ill_pid)
                    db.session.add(hossub)
                db.session.commit()
                    
                # 가입완료 페이지에서 id와 name을 표시하기 위함
                return redirect(url_for('auth.congrats', user_id=user.hos_cid, user_name=user.hos_name), code=307)
            else:
                flash('이미 존재하는 사용자입니다.')
                
        return render_template('auth/hospital_signup.html', form=form)
    
    else:
        return redirect(url_for('main.index'))


@bp.route('/congrats', methods=('GET', 'POST'))
def congrats():
    if request.method == 'POST' :
        user_id = request.args.get('user_id')
        request.get_data()
        user_name = request.args.get('user_name')
        print(user_id, user_name)
        return render_template('auth/congrats.html', user_id=user_id, user_name=user_name)
    else:
        return redirect(url_for('main.index'))


def login_required_all(view):
    """모든 사용자로 로그인 후 이용할 수 있는 서비스에 사용됨
    """
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('login.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view


def login_required_for_patient(view):
    """환자로 로그인 후 이용할 수 있는 서비스에 사용됨
    """
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is not None and type(g.user) == Hospital:
            return redirect(url_for('main.index'))
        return view(*args, **kwargs)
    return wrapped_view


def login_required_for_hospital(view):
    """병원으로 로그인 후 이용할 수 있는 서비스에 사용됨
    """
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is not None and type(g.user) == User:
            return redirect(url_for('main.index'))
        return view(*args, **kwargs)
    return wrapped_view

fhaa/views/change_views.py
"""
개인 정보 수정 페이지
"""
from flask import Blueprint, url_for, render_template, flash, request, session, g, Flask
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from fhaa import db
from fhaa.forms import UserUpdateForm, HospitalUpdateForm, UserDeleteForm, HospitalDeleteForm
from fhaa.models import User, Hospital, HosSub
from fhaa.views.auth_views import login_required_for_patient, login_required_all

bp = Blueprint('change', __name__, url_prefix='/change')

@bp.route('/')
def change():
    user_type = session.get('user_type')
    if user_type == "patient": # 일반 사용자 로그인
        return redirect(url_for('change.change_patient'))
    
    elif user_type == "hospital": # 병원 로그인
        return redirect(url_for('change.change_hospital'))
        
        
        

@bp.route('/patient/', methods=['GET', 'POST'])
@login_required_for_patient
def change_patient():
    
    user = User.query.filter_by(pat_ema=g.user.pat_ema)
    form = UserUpdateForm(name=g.user.pat_name, phone=g.user.pat_tel)
    
    if request.method == 'POST' and form.validate_on_submit():
        
        if check_password_hash(user.first().pat_pw, form.old_password.data):
            # 새로운 비밀번호가 존재할 경우 그 비밀번호로 변경
            if form.new_password1.data:
                user.update(dict(
                        pat_name=form.name.data, 
                        pat_pw=generate_password_hash(form.new_password1.data),
                        pat_tel=form.phone.data
                        ))
            # 새로운 비밀번호가 존재하지 않을 경우 기존 비밀번호를 다시 넣음
            else:
                user.update(dict(
                        pat_name=form.name.data, 
                        pat_pw=generate_password_hash(form.old_password.data),
                        pat_tel=form.phone.data
                        ))
                
            db.session.add(user.first())
            db.session.commit()
        else:
            flash('비밀번호가 일치하지 않습니다.')
        
        return redirect(url_for('change.change_patient'))
    
    return render_template('change/changeN.html', form=form)
    

    
@bp.route('/hospital/', methods=['GET', 'POST'])
def change_hospital():
    
    user = Hospital.query.filter_by(hos_cid=g.user.hos_cid)
    subject = HosSub.query.join(Hospital, Hospital.hos_cid==HosSub.hos_cid).filter(Hospital.hos_cid==g.user.hos_cid)
    form = HospitalUpdateForm(name=g.user.hos_name, address1=g.user.hos_addr1, address2=g.user.hos_addr2, tel=g.user.hos_tel)
    subjects = [ x.ill_pid for x in subject.all() ]
    
    if request.method == 'POST' and form.validate_on_submit():
        
        if check_password_hash(user.first().hos_pwd, form.old_password.data):
            
            # 새로운 비밀번호가 존재할 경우 그 비밀번호로 변경
            if form.new_password1.data:
                user.update(dict(
                        hos_name=form.name.data, 
                        hos_addr1=form.address1.data,
                        hos_addr2=form.address2.data,
                        hos_pwd=generate_password_hash(form.new_password1.data),
                        hos_tel=form.tel.data
                        ))
                
            # 새로운 비밀번호가 존재하지 않을 경우 기존 비밀번호를 다시 넣음
            else:
                user.update(dict(
                        hos_name=form.name.data, 
                        hos_addr1=form.address1.data,
                        hos_addr2=form.address2.data,
                        hos_pwd=generate_password_hash(form.old_password.data),
                        hos_tel=form.tel.data
                        ))
                
            for del_hossub in HosSub.query.filter_by(hos_cid=user.first().hos_cid).all():
                if type(del_hossub) is HosSub:
                    db.session.delete(del_hossub)
                
            for ill_pid in form.subject.data:
                add_hossub = HosSub(hos_cid=user.first().hos_cid, ill_pid=ill_pid)
                db.session.add(add_hossub)
                
            db.session.add(user.first())
            db.session.commit()
        else:
            flash('비밀번호가 일치하지 않습니다.')
        
        return redirect(url_for('change.change_hospital'))
    
    return render_template('change/changeH.html', form=form, subjects=subjects)
    
    
@bp.route('/signout/')
@login_required_all
def signout():
    user_type = session.get('user_type')
    if user_type == "patient": # 일반 사용자
        return redirect(url_for('change.signout_patient'))
    
    elif user_type == "hospital": # 병원 
        return redirect(url_for('change.signout_hospital'))
    
    
@bp.route('/signout/patient/')
@login_required_all
def signout_patient():
    print(session.get('user_id'))
    db.session.delete(User.query.filter_by(pat_ema=session.get('user_id')).first())
    db.session.commit()
    return redirect(url_for('login.logout'))


@bp.route('/signout/hospital/')
@login_required_all
def signout_hospital():
    user = Hospital.query.filter_by(hos_cid=g.user.hos_cid)
    
    print(session.get('user_id'))
    for del_hossub in HosSub.query.filter_by(hos_cid=user.first().hos_cid).all():
        if type(del_hossub) is HosSub:
            db.session.delete(del_hossub)
        
    db.session.delete(Hospital.query.filter_by(hos_cid=session.get('user_id')).first())
    db.session.commit() 
        
    return redirect(url_for('main.index'))

fhaa/views/log_views.py
from flask import Blueprint, render_template, session, request, flash, url_for, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from fhaa import db
from fhaa.forms import UserLoginForm, HospitalLoginForm
from fhaa.models import User, Hospital, Subject
import datetime

bp = Blueprint('login',__name__,url_prefix='/login')


@bp.route('/', methods=('GET','POST'))
def login():
    return render_template('log/login.html')


@bp.route('/pat/', methods=('GET','POST'))
def pat_login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(pat_ema=form.email.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.pat_pw, form.password.data):
            error = "비밀번호가 일치하지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.pat_ema
            session['user_type'] = "patient"
            print(user)
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('log/pat_login.html', form=form)


@bp.route('/hos/', methods=('GET','POST'))
def hos_login():
    form = HospitalLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = Hospital.query.filter_by(hos_cid=form.crn.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.hos_pwd, form.password.data):
            error = "비밀번호가 일치하지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.hos_cid
            session['user_type'] = "hospital"
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('log/hos_login.html', form=form)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))


# @bp.before_app_request
# def load_logged_in_user():
#     user_id = session.get('user_id')
#     user_type = session.get('user_type')
#     if user_id is None:
#         g.user = None
#         g.user_type = None
#     elif user_type == "patient":
#         g.user = User.query.get(user_id)
#         g.user_type = user_type
#         g.user_name = g.user.pat_name
#     elif user_type == "patient":
#         g.user = User.query.get(user_id)
#         g.user_type = user_type
#         g.user_name = g.user.pat_name
    
        

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    user_type = session.get('user_type')
    
    if user_id is None or user_type is None:
        g.user = None
        g.user_type = None
    else:
        g.user_type = user_type
        if user_type == 'patient':
            g.user = User.query.get(user_id)    
            # if g.user != None: 
            #     g.user_name = g.user.pat_name
            # else : 
            #     g.user_name = "guest"
            #     g.user = User.query.get(user_id)         
            # g.user_name = g.user.pat_name
            
        elif user_type == 'hospital':
            g.user = Hospital.query.get(user_id)
            # g.user_name = g.user.hos_name

fhaa/templates/base.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}" />
    <!-- FHAA CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>
    <!-- css Start -->
    {% block style %}
    {% endblock %}
    <!-- css End -->
    <title>FHAA</title>
  </head>

<body class="d-flex flex-column min-vh-100">
    <!-- navbar 네비게이션바 -->
    {% include "navbar.html" %}


    <!-- content(기본 템플릿 안에 삽입될 내용) Start -->
    {% block content %}
    {% endblock %}
    <!-- content(기본 템플릿 안에 삽입될 내용) End -->

    
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}    
    <!-- 자바스크립트 End -->
    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='bootstrap.bundle.min.js') }}"></script>

    <!-- Footer -->
    <footer class="bg-primary py-5 mt-auto">
      <p class="m-0 text-center text-white">Copyright &copy; Find Hospital Anytime, Anywhere; FHAA</p>
    </footer>
</body>

</html>

fhaa/templates/form_errors.html
<!-- field 오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
  {% for field, errors in form.errors.items() %}
  <strong>{{ form[field].label }}</strong>
  <ul>
    {% for error in errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
  {% endfor %}
</div>
{% endif %}

<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">{{ message }}</div>
{% endfor %}

fhaa/templates/navbar.html
<div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
    <div class="container">
        <a href="{{ url_for('main.index') }}" class="navbar-brand">FHAA</a>
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <!-- 환자일 경우에는 의뢰하기, 응답한 병원 목록만 네비바에 표시 -->
                {% if g.user_type == 'patient' %}      
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('request.user_req') }}">진료요청</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('request.hospital_list') }}">병원목록</a>
                    </li>
                <!-- 병원일 경우 들어온 의뢰 페이지만 네비바에 표시 -->
                {% else %}
                    <li>
                        <a class="nav-link" href="{{url_for('request.board')}}">요청목록</a> 
                    </li>
                {% endif %}

                <!-- 매칭상태는 환자/병원 모두 표시 -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('request.matching') }}">매칭상태</a>
                </li>
            
            </ul>
            <ul class="navbar-nav ms-md-auto">
                <!-- 로그인을 한 상태이면 -->
                {% if g.user %}
                    <li class="nav-item dropdown">
                        {% if g.user_type == "patient" %}
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" id="user">{{ g.user.pat_name }} 님</a>
                        {% else %}
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" id="user">{{ g.user.hos_name }} 님</a>
                        {% endif %} 
                        <div class="dropdown-menu" aria-labelledby="user">
                            <a class="dropdown-item" href="{{ url_for('login.logout')}}">로그아웃</a>
                            <a class="dropdown-item" href="{{ url_for('change.change') }}">개인정보수정</a>
                        </div>
                    </li>
                <!-- 로그인을 하지 않은 상태이면 -->
                {% else %}
                    <li class="nav-item">
                        <a rel="noopener" class="nav-link" href="{{ url_for('auth.signup') }}">회원가입</a>
                    </li>
                    <li class="nav-item">
                        <a rel="noopener" class="nav-link" href="{{ url_for('login.login') }}">로그인</a>
                    </li>
                {% endif %} 
            </ul>
        </div>
    </div>
</div>