fhaa/views/log_views.py
from flask import Blueprint, render_template, session, request, flash, url_for, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from fhaa import db
from fhaa.forms import UserLoginForm, HospitalLoginForm
from fhaa.models import User, Hospital, Subject
import datetime

bp = Blueprint('login',__name__,url_prefix='/login')


@bp.route('/', methods=('GET','POST'))
def login():
    return render_template('log/login.html')


@bp.route('/pat/', methods=('GET','POST'))
def pat_login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(pat_ema=form.email.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.pat_pw, form.password.data):
            error = "비밀번호가 일치하지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.pat_ema
            session['user_type'] = "patient"
            print(user)
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('log/pat_login.html', form=form)


@bp.route('/hos/', methods=('GET','POST'))
def hos_login():
    form = HospitalLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = Hospital.query.filter_by(hos_cid=form.crn.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.hos_pwd, form.password.data):
            error = "비밀번호가 일치하지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.hos_cid
            session['user_type'] = "hospital"
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('log/hos_login.html', form=form)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))


# @bp.before_app_request
# def load_logged_in_user():
#     user_id = session.get('user_id')
#     user_type = session.get('user_type')
#     if user_id is None:
#         g.user = None
#         g.user_type = None
#     elif user_type == "patient":
#         g.user = User.query.get(user_id)
#         g.user_type = user_type
#         g.user_name = g.user.pat_name
#     elif user_type == "patient":
#         g.user = User.query.get(user_id)
#         g.user_type = user_type
#         g.user_name = g.user.pat_name
    
        

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    user_type = session.get('user_type')
    
    if user_id is None or user_type is None:
        g.user = None
        g.user_type = None
    else:
        g.user_type = user_type
        if user_type == 'patient':
            g.user = User.query.get(user_id)    
            # if g.user != None: 
            #     g.user_name = g.user.pat_name
            # else : 
            #     g.user_name = "guest"
            #     g.user = User.query.get(user_id)         
            # g.user_name = g.user.pat_name
            
        elif user_type == 'hospital':
            g.user = Hospital.query.get(user_id)
            # g.user_name = g.user.hos_name

fhaa/views/request_views.py
from flask import Blueprint, render_template, session, request, flash, url_for, g, Flask
from werkzeug.utils import redirect
from fhaa.models import Request, Subject, Hospital, HosSub, Matching
import time, datetime
from fhaa import db
from fhaa.views.auth_views import login_required_for_patient, login_required_for_hospital, login_required_all
from fhaa.libs import gps



bp = Blueprint('request', __name__, url_prefix='/request')


@bp.route('/', methods = ['GET'])    
@login_required_for_patient
def user_req() :
    addr_now = "경기도 군포시 산본천로 12"
    sub = Subject.query.all()
    return render_template('request/user_req.html',addr_now= addr_now, sub=sub)


@bp.route('/', methods = ['POST'])    
def req_post() :
    addr_now = request.form.get('location')
    f_req_type = request.form.get('req_type')
    f_req_time = request.form.get('req_time')
    f_pat_ema = session.get('user_id')
    f_req_date= datetime.datetime.now()
    f_req_req= request.form.get('req_req')
    
    # 가까운 병원 목록 만들기
    # update by jlee <junlee9834@gmail.com>
    location_lat = float(request.form.get('location_lat'))
    location_lon = float(request.form.get('location_lon'))
    lat_KM = 0.0091
    lon_KM = 0.0113
    hospitals = Hospital.query.join(HosSub).join(Subject)\
        .filter(Subject.ill_type==f_req_type)\
        .filter(Hospital.hos_lat >= location_lat-lat_KM, Hospital.hos_lat <= location_lat+lat_KM)\
        .filter(Hospital.hos_lnt >= location_lon-lon_KM, Hospital.hos_lnt <= location_lon+lon_KM)
    
    if hospitals.first() == None:
        error = "인근의 병원을 찾을 수 없습니다. 다른 위치에서 다시 시도해주세요."
        flash(error)
        return redirect(url_for('request.req_post'))
    else:
        for hospital in hospitals:
            # 환자 <-> 병원 거리
            distance = gps.compare((location_lat, location_lon), (hospital.hos_lat, hospital.hos_lnt))
            if distance < 1.:
                distance = 0.            
            r = Request(
                    req_type = f_req_type, 
                    req_loc = addr_now,
                    req_time = f_req_time,
                    req_req= f_req_req,
                    pat_ema = f_pat_ema,
                    req_date = f_req_date,
                    hos_cid = hospital.hos_cid,
                    req_dist = distance
                )
            db.session.add(r)          
        db.session.commit() 
        
    return redirect(url_for('request.hospital_list'))



@bp.route('/detail/<int:request_id>/')
def detail(request_id):
    # request_list = Request.query.get_or_404(request_id)

    return render_template('request/user_detail.html', request=request)


@bp.route('/board/', methods = ['POST', 'GET'])   
@login_required_all
@login_required_for_hospital
def board():
    
    if request.method == 'POST':
        check = request.form.get('check')

        if check == "accept":
            f_req_id = request.form.get('req_id')
            request_ = Request.query.filter_by(req_id=f_req_id)
            
            # request_.first()가 None 경우 == 받은 req_id의 데이터가 이미 삭제되었을 경우
            if request_.first() == None:
                error = "이미 진료 희망시간으 초과해 만료된 요청입니다."
                flash(error)
                return redirect(url_for('request.board'))
            
            # 현재 시간과 req_date+req_time을 비교하여 현재 시간이 더 크면 불가해야함     
            # 병원이 새로고침을 하지 않은 상태라면 `진료 요청시간`을 넘겼음에도 수락이 되기 때문에
            # 아래와 같이 현재 시간과 비교하여 처리함
            req_time = datetime.timedelta(minutes=int(request_.first().req_time))
            req_limit_time = request_.first().req_date + req_time   
            if datetime.datetime.now() > req_limit_time:
                error = "이미 진료 희망시간을 초과하였습니다."
                db.session.delete(request_.first())
                db.session.commit()
                    
            else:
                request_.update(dict(req_chk=0))
                db.session.add(request_.first())
                db.session.commit()
                
        else:
            f_req_id = request.form.get('req_id')
            request_ = Request.query.filter_by(req_id=f_req_id)
            # request_.first()가 None 경우 == 받은 req_id의 데이터가 이미 삭제되었을 경우
            if request_.first() == None:
                return redirect(url_for('request.board'))
            db.session.delete(request_.first())
            db.session.commit()
            
        return redirect(url_for('request.board'))
    
    page = request.args.get('page', type=int, default=1)  # 페이지
    request_list = Request.query.filter_by(hos_cid=g.user.hos_cid, req_chk=1)
    request_list = request_list.paginate(page=page, per_page=10)

    return render_template('request/user_list.html', request_list=request_list)



@bp.route('/hospitals/', methods = ['POST', 'GET'])   
def hospital_list():
    """환자 관점에서 환자의 의뢰를 수락한 병원들의 목록을 보여줌.

    Returns:
        render_template: request/hospital_list.html
        
    Authors: jlee <junlee9834@gmail.com>
    """
    
    if request.method == 'POST':
        check = request.form.get('check')
        
        # 환자가 `O` 버튼을 누르면
        if check == "accept":
            f_req_id = request.form.get('req_id')
            request_ = Request.query.filter(Request.req_id==f_req_id).first()

            # Matching 테이블에 데이터 생성
            matching = Matching(
                req_id=request_.req_id, 
                pat_ema=request_.pat_ema, 
                hos_cid=request_.hos_cid
            )
            db.session.add(matching)
            
            # outerjoin 후 mat_id가 빈 것(매칭되지 않은 것)만 가져옴 
            # Request 테이블에서 매칭되지 않은 의뢰를 제거
            request_del =  Request.query.outerjoin(Matching).filter(
                Request.pat_ema==request_.pat_ema,
                Request.req_date==request_.req_date, 
                Request.req_type==request_.req_type, 
                Matching.mat_id==None
            )
            for r in request_del.all():
                db.session.delete(r)
                
            db.session.commit()

        # 환자가 `X` 버튼을 누르면
        else:
            # Request 테이블에서 해당 요청을 제거
            f_req_id = request.form.get('req_id')
            request_ = Request.query.filter_by(req_id=f_req_id)
            db.session.delete(request_.first())
            db.session.commit()
            
        return redirect(url_for('request.hospital_list'))
            
            
    page = request.args.get('page', type=int, default=1)  # 페이지
    
    # 이미 매칭된 request는 나오지 않도록 해야 함
    # outerjoin 후 mat_id가 빈 것(매칭되지 않은 것)만 가져옴 
    # 그리고 가까운 거리순으로 정렬함
    request_list =  Request.query.outerjoin(Matching).filter(
        Request.pat_ema==g.user.pat_ema, 
        Request.req_chk==0,    
        Matching.mat_id==None
    ).order_by(Request.req_dist)

    request_list = request_list.paginate(page=page, per_page=10)

    return render_template('request/hospital_list.html', request_list=request_list, datetime=datetime)


@bp.route('/match/status/')
@login_required_all
def matching():
    '''환자와 병원 모두 현재 매칭 상태를 보여줌.
    '''
    page = request.args.get('page', type=int, default=1)  # 페이지

    if g.user_type == "patient":
        matching_list = Matching.query.filter(Matching.pat_ema==g.user.pat_ema)
    elif g.user_type == "hospital":
        matching_list = Matching.query.filter(Matching.hos_cid==g.user.hos_cid)
    else:
        return redirect(url_for('main.index'))
     
    matching_list = matching_list.paginate(page=page, per_page=10)

    return render_template('request/match_status.html', matching_list=matching_list)



@bp.route('/match/done/')
@login_required_all
def match_():
    if request.method == 'POST' :
        user_id = request.args.get('user_id')
        user_name = request.args.get('user_name')
        return render_template('auth/congrats.html', user_id=user_id, user_name=user_name)
    else:
        return redirect(url_for('main.index'))

fhaa/templates/request/hospital_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="margin-top: 7rem;">
    <!-- 질문 목록 -->
    <div class="container my-3">
        <table class="table">
            <h2 class="ml-auto">병원목록</h2>
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                진료요청을 수락한 병원들의 목록입니다.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <thead>
            <tr class="table-secondary">
                <th>순번</th>
                <th>진료과목</th>
                <th>병원명</th>
                <th>병원 위치</th>
                <th>거리</th>
                <th>전화번호</th>
                <th>선택</th>
            </tr>
            </thead>
            <tbody>
            {% if request_list %}
                {% for request in request_list.items %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td><a>{{ request.req_type }}</a></td>
                    <td><a>{{ request.hospital.hos_name }}</a></td>
                    {% if request.hospital.hos_addr2 %}
                        <td> {{ ", ".join((request.hospital.hos_addr1,request.hospital.hos_addr2)) }}</td>
                    {% else %}
                        <td> {{ request.hospital.hos_addr1 }}</td>
                    {% endif %}
                    <td>약 {{ request.req_dist }}m</td>
                    <td>{{ request.hospital.hos_tel }}</td>
                    <td>
                        <div class="d-flex">
                            <form action="{{ url_for('request.hospital_list') }}" method="POST">
                                <input type="text" class="form-control" name="req_id" id="req_id" value="{{request.req_id}}" hidden>
                                <input type="text" class="form-control" name="check" id="accept" value="accept" hidden>
                                <button type="submit" class="btn btn-outline-success">◯</button>
                            </form>
                            <form action="{{ url_for('request.hospital_list') }}" method="POST">
                                <input type="text" class="form-control" name="req_id" id="req_id" value="{{request.req_id}}" hidden>
                                <input type="text" class="form-control" name="check" id="delete" value="delete" hidden>
                                <button type="submit" class="btn btn-outline-danger">⨉</button>
                            </form>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

fhaa/templates/request/match_status.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="margin-top: 7rem;">
    <!-- 질문 목록 -->
    <div class="container my-3">
        <table class="table">

            <h2 class="ml-auto">매칭상태</h2>
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                매칭된 정보들의 목록입니다.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            
            <thead>
            <tr class="table-secondary">
                <th>순번</th>
                <th>환자 email</th>
                <th>진료과목</th>
                <th>병원명</th>
                <th>병원주소</th>
                <th>진료 희망시간</th>
            </tr>
            </thead>
            <tbody>
            {% if matching_list %}
            {% for request in matching_list.items %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ request.pat_ema }}</td>
                    <td>{{ request.req.req_type }}</td>
                    <td>{{ request.hospital.hos_name }}</td>
                    {% if request.hospital.hos_addr2 %}
                        <td> {{ ", ".join((request.hospital.hos_addr1,request.hospital.hos_addr2)) }}</td>
                    {% else %}
                        <td> {{ request.hospital.hos_addr1 }}</td>
                    {% endif %}
                    {% set args = { 'req_date': request.req.req_date, 'req_time': request.req.req_time } %}
                    <td>{{ args | add_datetime }}</td>
                </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

fhaa/templates/request/matched.html
{% extends "base.html" %}
{% block content %}
<!-- Authors: jlee (junlee9834@gmail.com) -->
<div class="container d-flex flex-column align-items-center" style="margin-top: 7rem;">
    <div class="container primary" style="border-bottom: 1px solid;">
        <h3 class="text-center">매칭이 완료되었습니다.</h3>
    </div>

    <img class='w-25' src="{{ url_for('static', filename='check.png' ) }}">
    <table class="table w-25 mt-5">
        <tbody>
            <tr class="table-light">
                <th scope="row">병원명</th>
                <td></td>
            </tr>
            <tr class="table-light">    
                <th scope="row">진료과목</th>
                <td></td>
            </tr><tr class="table-light">
                <th scope="row">병원 주소</th>
                <td></td>
            </tr>
        </tbody>
    </table>

    <div class="container d-flex flex-row justify-content-center mt-5 w-25" >
        <a href="{{ url_for('main.index') }}" class="btn btn-primary m-1 w-50">메인페이지</a>
        <a href="{{ url_for('login.login') }}" class="btn btn-primary m-1 w-50">로그인</a>
    </div>
</div>
{% endblock %}

fhaa/templates/request/user_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ request.req_type }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ request.req_rid }}</div>
            <div class="d-flex justify-content-end">
                <!-- <div class="badge bg-light text-dark p-2">
                    {{ request.req_rid }}
                </div> -->
            </div>
        </div>
    </div>

    <form action="{{ url_for('request.board', request_id=request.req_rid) }}" method="post" class="my-3">
        <div class="mb-3">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <div class="row gy-5">
            <div class="col">
                <button type="submit" class="btn btn-primary" style="width:100%" >수락</button>
            </div>
            <div class="col">
                <button type="submit" class="btn btn-primary" style="width:100%" >거절</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}
{% block script %}
<script>

</script>
{% endblock %}

fhaa/templates/request/user_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="margin-top: 7rem;">
    <!-- 질문 목록 -->
    <div class="container my-3">
        <table class="table">

            <h2 class="ml-auto">요청목록</h2>
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                진료를 요청한 환자들의 목록입니다.</p> <!-- 줄 바꿈 용도의 p tag -->
                요청사항을 클릭해 자세한 내용을 확인할 수 있습니다.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            
            <!-- flash 오류 -->
            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% endfor %}

            <thead>
            <tr class="table-secondary">
                <th>순번</th>
                <th>환자 email</th>
                <th>진료과목</th>
                <th>환자 현재 위치</th>
                <th>진료 희망시간</th>
                <th>요청사항</th>
                <th>선택</th>

            </tr>
            </thead>
            <tbody>
            {% if request_list %}
            {% for request in request_list.items %}
            <tr id="{{ request.req_id }}">
                <td>{{ loop.index }}</td>
                <td>
                    <a href="{{ url_for('request.detail', request_id=request.req_id) }}">{{ request.pat_ema }}</a>
                </td>
                <td>{{ request.req_type }}</td>
                <td>{{ request.req_loc }}</td>
                {% set args = { 'req_date': request.req_date, 'req_time': request.req_time } %}
                <td>{{ args | add_datetime }}</td>
                <!-- test -->
                <td class="w-25 text-left">
                    <div class="panel-faq-container">
                        <p class="panel-faq-title text-primary">{{ request.req_req | truncate(20) }}</p>
                        <div class="panel-faq-answer">
                            <p>{{ request.req_req }}</p>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="btn-group" role="group">
                        <form class="mr-1" action="{{ url_for('request.board') }}" method="POST">
                            <input type="text" class="form-control" name="req_id" id="req_id" value="{{request.req_id}}" hidden>
                            <input type="text" class="form-control" name="check" id="accept" value="accept" hidden>
                            <button type="submit" class="btn btn-outline-success">◯</button>
                        </form>
                        <br/>
                        <form action="{{ url_for('request.board') }}" method="POST">
                            <input type="text" class="form-control" name="req_id" id="req_id" value="{{request.req_id}}" hidden>
                            <input type="text" class="form-control" name="check" id="delete" value="delete" hidden>
                            <button type="submit" class="btn btn-outline-danger">⨉</button>
                        </form>
                    </div>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">목록이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
    <!-- {% if request_list %}
        <ul>
        {% for request in request_list.items %}
            <li><a href="{{ url_for('request.detail', request_id=request.req_id) }}">{{ request.req_type }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>질문이 없습니다.</p>
    {% endif %} -->
</div>
{% endblock %}


{% block script %}
<script>
window.onload = () => {
// panel-faq-container
const panelFaqContainer = document.querySelectorAll(".panel-faq-container"); // NodeList 객체

// panel-faq-answer
let panelFaqAnswer = document.querySelectorAll(".panel-faq-answer");

// btn-all-close
const btnAllClose = document.querySelector("#btn-all-close");

// 반복문 순회하면서 해당 FAQ제목 클릭시 콜백 처리
for( let i=0; i < panelFaqContainer.length; i++ ) { 
    panelFaqContainer[i].addEventListener('click', function() { // 클릭시 처리할 일 
        // FAQ 제목 클릭시 -> 본문이 보이게끔 -> active 클래스 추가
    panelFaqAnswer[i].classList.toggle('active');
    });
    };

    btnAllClose.addEventListener('click', function() {
    // 버튼 클릭시 처리할 일
    for(let i=0; i < panelFaqAnswer.length; i++) { panelFaqAnswer[i].classList.remove('active'); }; }); }
</script>
{% endblock %}

{% block style %}
<style>
.panel-faq-container {
margin-bottom: -16px;
}
.panel-faq-title {
cursor: pointer;
overflow: hidden;
white-space: nowrap;
}
.panel-faq-answer {
height: 0;
overflow: hidden;
/* 변화가 시작되는 쪽에다가 transition 적용해준다 0 -> 300px
왜? 닫기 버튼을 누를 때 변화가 티남 */
transition: all 0.3s;
}
#btn-all-close {
margin-bottom: 10px;
border: none;
cursor: pointer;
padding: 10px 25px;
float: right;
}
#btn-all-close:hover {
background-color: yellow;
color: #000;
transition: all 0.2;
}
.active {
display: block;
/* 높이를 정해줘야지만 transition이 적용됨 */
height: 100px;
overflow: scroll;
}
</style>
{% endblock %}

fhaa/templates/request/user_req.html
{% extends 'base.html'%}

{% block content %}
<div class="container w-50 mb-3" style="margin-top: 8rem">
  <div class="w-100 col-md-7 col-md-offset-2">

    <div class="page-hearder" style="padding-bottom: 20px">
      <h3>진료요청</h3>
    </div>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      인근의 병원에 진료를 요청합니다.
      위치 액세스 허용이 필요합니다.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">{{ message }}</div>
    {% endfor %}
    
    <form action="{{ url_for('request.req_post') }}" method="POST">
      <div class="mb-3">의뢰인 : {{ g.user.pat_name }}</div>
      <div class="mb-3">
        <div class="d-flex">
          <input
            type="text"
            class="form-control"
            name="location"
            id="location"
            onchange="setLocation();"
            readonly
          />
          <!--위도-->
          <input
            type="text"
            class="form-control"
            name="location_lat"
            id="location_lat"
            hidden
          />
          <!--경도-->
          <input
            type="text"
            class="form-control"
            name="location_lon"
            id="location_lon"
            hidden
          />
          <input
            type="button"
            class="btn btn-primary"
            onclick="getDaumPostcode();"
            value="주소 검색"
          />
        </div>

        <!-- Map -->
        <div class="w-100" id="map" style="height: 400px"></div>
      </div>

      <div class="mb-3">
        희망시간
        <select class="form-select" name="req_time">
          <option value="" selected>-- 선택 --</option>
          <option value="10">10분내외</option>
          <option value="30">30분내외</option>
          <option value="60">60분내외</option>
        </select>
      </div>

      <div class="mb-3">
        진료과목
        <select class="form-select" name="req_type">
          <option value="" selected>-- 선택 --</option>
          {% for sub_item in sub %}
          <option value="{{sub_item.ill_type}}">{{sub_item.ill_type}}</option>
          {% endfor %}
        </select>
      </div>

      요청사항
      <div class="mb-3">
        <textarea
          name="req_req"
          class="form-control"
          rows="3"
          placeholder="요청사항을 입력해주세요."
        ></textarea>
      </div>

      <tr class="d-flex flex-column">
        <td class="text-center" colspan="2">
          <input
            class="btn btn-primary w-25"
            type="submit"
            onclick="finish()"
            value="의뢰등록"
          />

          <input
            class="btn btn-primary w-25"
            margin-left:
            10px;
            type="reset"
            value="다시작성"
          />
        </td>
      </tr>
    </form>
  </div>
</div>
{% endblock %}

{% block script %}
<script>
  function finish() {
    alert("병원에 진료 요청이 완료되었습니다.");
  }
</script>
<script
  type="text/javascript"
  src="//dapi.kakao.com/v2/maps/sdk.js?appkey=a402faa3e887603d2d2e512be8b710d1&libraries=services"
></script>
<script
  type="text/javascript"
  src="{{ url_for('static', filename='map.js') }}"
></script>
<script
  type="text/javascript"
  src="{{ url_for('static', filename='address.js') }}"
></script>
<script
  type="text/javascript"
  src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"
></script>
{% endblock %}